services:
  - type: web
    name: essai2-laravel
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan migrate --force
      php artisan storage:link
    startCommand: |
      php artisan serve --host 0.0.0.0 --port $PORT
